var navs = [{
	"title": "基本元素",
	"icon": "fa-cubes",
	"spread": true,
	"children": [{
		"title": "按钮",
		"icon": "&#xe641;",
		"href": "/templates/admin/button.html"
	}, {
		"title": "表单",
		"icon": "&#xe63c;",
		"href": "/templates/admin/form.html"
	}, {
		"title": "表格",
		"icon": "&#xe63c;",
		"href": "/templates/admin/table.html"
	}, {
		"title": "导航",
		"icon": "&#xe609;",
		"href": "/templates/admin/nav.html"
	}, {
		"title": "Tab选项卡",
		"icon": "&#xe62a;",
		"href": "/templates/admin/tab.html"
	}, {
		"title": "辅助性元素",
		"icon": "&#xe60c;",
		"href": "/templates/admin/auxiliar.html"
	}]
}, {
	"title": "组件",
	"icon": "fa-cogs",
	"spread": false,
	"children": [{
		"title": "Datatable",
		"icon": "fa-table",
		"href": "/templates/admin/begtable.html"
	}, {
		"title": "Navbar组件",
		"icon": "fa-navicon",
		"href": "/templates/admin/navbar.html"
	}, {
		"title": "Laytpl+Laypage",
		"icon": "&#xe628;",
		"href": "/templates/admin/paging.html"
	}]
}, {
	"title": "第三方组件",
	"icon": "&#x1002;",
	"spread": false,
	"children": [{
		"title": "iCheck组件",
		"icon": "fa-check-square-o",
		"href": "/templates/admin/icheck.html"
	}]
}, {
	"title": "地址本",
	"icon": "fa-address-book",
	"href": "/templates/admin/",
	"spread": false,
	"children": [{
		"title": "Github",
		"icon": "fa-github",
		"href": "https://www.github.com/"
	}, {
		"title": "QQ",
		"icon": "fa-qq",
		"href": "http://www.qq.com/"
	}, {
		"title": "Fly社区",
		"icon": "&#xe609;",
		"href": "http://fly.layui.com/"
	}, {
		"title": "新浪微博",
		"icon": "fa-weibo",
		"href": "http://weibo.com/"
	}]
}, {
	"title": "这是一级导航",
	"icon": "fa-stop-circle",
	"href": "https://www.baidu.com",
	"spread": false
}];